"""create user and blof tables

Revision ID: 7377c5e037a9
Revises:
Create Date: 2023-07-02 23:33:23.280043

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7377c5e037a9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
